### PR TITLE
Use files, and add rimraf

### PR DESCRIPTION
**Pull request by XhmikosR**
@EvanHahn 

Not sure if I'll be able to do this for all the packages here, but `rm -rf` isn't cross-platform and rimraf is already in devDependencies anyway.

So this actually fixes things on Windows.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@EvanHahn: I also made the engines change because it's really fine.

Now, I see that you don't test on Node.js 4 on Travis. It's bad doing so IMO. Something not tested will break without anyone noticing.


You know your versions support better, just sort this out later by either testing on 4.0 too or dropping support for 4.0 later.

**Comment by XhmikosR** [comment]
2. >=4.0.0 is equal to >=4
3. the same as with .npmignore

No, sorry, I don't have the time to split this. It's simple changes.

**Comment by XhmikosR** [comment]
BTW, you always pull the branch locally to see the output of `npm pack --dry`.

**Comment by EvanHahn** [comment]
Because I don't intend to merge this (it needs to be split up into smaller PRs), I'm going to close this.

Feel free to open issues for each of these things and we can address them individually.

**Comment by XhmikosR** [comment]
Nah, all good.

**Pull request closed without merging**
