### PR TITLE
Contributors: Add Nathan Shively-Sanders (@sandersn)

### PR DESCRIPTION
**Pull request by sandersn**

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thanks! Would you like to add yourself to the [main contributors list](https://helmetjs.github.io/contributors), too?

**Comment by EvanHahn** [comment]
I'm also happy to do that on your behalf if you'd prefer.

**Comment by sandersn** [comment]
Sure, that would be nice.

**Comment by EvanHahn** [comment]
[Done!](https://github.com/helmetjs/helmetjs.github.io/commit/9e96f61627d228684971167bbca9725f4d87cd1e) Thanks again for your help.

**Pull request merged**
